name: Application build and test
on:
    push:
        paths-ignore:
            - '.github/**'
env:
    java_version: '17'
    mvn_parameter: '-B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn'
    image_name: 'quay.io/heubeck/examiner'
jobs:
    ci:
        name: Application Build
        runs-on: ubuntu-latest
        if: github.actor != 'dependabot[bot]'
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Setup Java
              uses: actions/setup-java@v3
              with:
                  java-version: '${{ env.java_version }}'
                  distribution: 'temurin'

            - name: Application Build and Test
              run: |
                  mvn ${{ env.mvn_parameter }} clean verify -Pnative,dependency-scan
                  VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.version -q -DforceStdout)
                  echo VERSION="$VERSION" >> $GITHUB_ENV

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to quay.io
              uses: docker/login-action@v2
              if: github.ref == 'refs/heads/main'
              with:
                  registry: quay.io
                  username: ${{ secrets.QUAY_USER }}
                  password: ${{ secrets.QUAY_PASSWORD }}

            - name: Docker build
              uses: docker/build-push-action@v3
              with:
                  context: .
                  file: src/main/docker/Dockerfile
                  tags: |
                      ${{ env.image_name }}:${{ env.VERSION }}
                      ${{ env.image_name }}:latest
                  platforms: linux/amd64,linux/arm64
                  load: ${{ github.ref != 'refs/heads/main' }}
                  push: ${{ github.ref == 'refs/heads/main' }}
